### ISSUE TITLE
[BUG] Failure for CoC7; I don't get prompted for the fields.  

### ISSUE THREAD

**Issue by saanvik** [arcanistzed/pdf-sheet#2]
Trying to print a character sheet; upload doesn't seem to be working correctly.  

**To Reproduce**
1. Install and enable the module
2. Go to Configure Settings; note error related to invalid JSON.  In Module Settings for Export to PDF, the JSON says "undefined"
3. Double click on a character to see the sheet.
4. Click "Export to PDF"
5. Dialog box opens; click "Choose File" and select the file.  
6. Nothing happens.
7. Click "Close"
8. Nothing happens.  

**Expected behavior**
I *think* what's supposed to happen is I get prompted with the fields to fill out for mapping.  

**Screenshots**
[CoC - 7th Edition Character Sheet - Fillable.pdf](https://github.com/arcanistzed/pdf-sheet/files/7010931/CoC.-.7th.Edition.Character.Sheet.-.Fillable.pdf)

**Foundry VTT version:**
0.8.8

**Additional context**
game system https://github.com/HavlockV/CoC7-FoundryVTT/
Note that not all CoC character sheets can be filled without Acrobat; this one can be.

**Comment by saanvik** [comment]
[actor-json.zip](https://github.com/arcanistzed/pdf-sheet/files/7010971/actor-json.zip)

Adding the json export of the acting in case that helps.

**Comment by arcanistzed** [comment]
I believe this is fixed in 0.1.3
Let me know if you still have issues

**Comment by saanvik** [comment]
Confirmed, that resolved the problem.
