### ISSUE TITLE
[FEAT] Reverse conversion from pdf to foundry

### ISSUE THREAD

**Issue by bnp800** [arcanistzed/pdf-sheet#22]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Reverse conversion from pdf to foundry.

**Describe alternatives you've considered**
Since we have mappings for pdf, I think this won't be difficult.

**Additional context**

**Comment by arcanistzed** [comment]
I think it would still be difficult, but I love the idea!

**Comment by arcanistzed** [comment]
Upon further thought, this doesn't seem possible unless a new mapping were created for the majority of fields.

**Comment by arcanistzed** [comment]
I'm going to close this since I believe it is out of scope. Feel free to use the mappings created here for a different project that does this!
