### ISSUE TITLE
[Bug]: Spellsheet not exported properly

### ISSUE THREAD

**Issue by ChrisAndelin** [arcanistzed/pdf-sheet#46]
### Expected Behavior

The spellsheet list of spell names should match the list of spells in the Foundry spell sheet. Also the prepared spells indicated should match.

### Current Behavior

Using the mapping for dnd5e in the module as well as the one indicated on the Github page, there are some spells missing and a wrong indication of which spells are prepared.

### Steps to Reproduce

Create a dnd 5e character sheet with spells and some of them prepared
Export the sheet using any of the mappings indicated in the current behavior description
Compare the spell lists' names and prepared indications
Observe the mismatch

(If you need my specific repro I'll be glad to provide a character foundry export if that works)

### Version

0.20.0

### Foundry VTT Version

9.269

### Operating System

Windows

### Browser / App

Chrome

### Game System

dnd52 1.6.3

### Modules Disabled

- [ ] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Could you upload some screenshots of the difference?

**Comment by ChrisAndelin** [comment]
Hope this helps.
![image](https://user-images.githubusercontent.com/3412654/175208791-279410ba-f5a2-4fc7-9e2c-57b0fede5138.png)
![image](https://user-images.githubusercontent.com/3412654/175208867-18d94fbd-a4d2-448a-a186-648b357e82a9.png)

**Comment by ChrisAndelin** [comment]
![image](https://user-images.githubusercontent.com/3412654/175209159-ee3daa79-193d-4f11-8796-e246d269b738.png)
Here's an entire list of the spells (including non-prepared) from the spell list tab.

I can't remember which of the two mappings this pdf was created from but it was one of the two mentioned in the description.
