### ISSUE TITLE
[Bug]: german dnd5e: PDF Sheet | Invalid mapping Javascript Object

### ISSUE THREAD

**Issue by RandomLegend** [arcanistzed/pdf-sheet#67]
### Expected Behavior

Export the charactersheet as PDF.

### Current Behavior

![2023-02-11_21-46](https://user-images.githubusercontent.com/38812603/218280498-522e837b-8ca2-49f7-ace4-7e6de93b3e42.png)

Throws this error upon trying to export.

![image](https://user-images.githubusercontent.com/38812603/218280515-046841c0-e4b2-4da5-9e48-0e856f69d89b.png)

Already tried this PR: https://github.com/manolitto/pdf-sheet/blob/4bd4ab8dc800952877fbbe2804b3ca6491e16abe/mappings/dnd5e-charakterbogen_ataendler_v2.8.2.mapping with the correct .PDF file

### Steps to Reproduce

1. Go to Settings
2. Change mapping to dnd5e-charakterbogen-ataendler...
3. Open actor
4. Export PDF
5. chose .PDF file
6. Get error

### Version

current

### Foundry VTT Version

10.281

### Operating System

Linux / ubuntuserver

### Browser / App

Chrome, Firefox

### Game System

dnd5e

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by Apewert** [comment]
Please use my fixed version of the mapping. It works best with version 2.8.1 of the ataendler sheet.
I hope that arcanistzed will update the mapping in the repo and replace it with my fixed one.
[dnd5e-charakterbogen_ataendler_v2.8.1_v4.txt](https://github.com/arcanistzed/pdf-sheet/files/10715117/dnd5e-charakterbogen_ataendler_v2.8.1_v4.txt)

**Comment by RandomLegend** [comment]
Perfectly - that works nice!
Thanks
