### ISSUE TITLE
[Query] Syntax for applying floor() or int() to a mapping

### ISSUE THREAD

**Issue by Dick-K** [arcanistzed/pdf-sheet#8]
Hi, I like your module and am having some success writing a mapping json for HavelockV's Call of Cthulhu system. I'm not even slightly a javascript expert and have hit a wall trying to apply either floor() or int() to the following line:

 { "pdf": "STR_half", "foundry": @data.characteristics.str.value/2 }

Note that the STR_half value is derived and not present in the actor data. I would like the line to return half the Strength characteristic rounded down. At the moment it returns the float value, e.g. Strength 61 returns 30.5. 

I have tried:

 { "pdf": "STR_half", "foundry": floor( @data.characteristics.str.value/2 ) }
and
 { "pdf": "STR_half", "foundry": @data.characteristics.str.value/2.floor() }

...but these return mapping errors or "floor is not a function".

Any chance you could give me a hint on how to apply a function here? Many thanks for your time and trouble.

**Comment by arcanistzed** [comment]
You need to use `{ "pdf": "STR_half", "foundry": Math.floor(@data.characteristics.str.value / 2) }`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor

**Comment by Dick-K** [comment]
Much obliged, that worked nicely, thanks for the rapid reply, all the best.
