### ISSUE TITLE
[Bug]: Export button not displayed in Cypher System

### ISSUE THREAD

**Issue by trevorschadt** [arcanistzed/pdf-sheet#83]
### Expected Behavior

Given:
- A world is created using the Cypher System;
- The "Export Sheet to PDF" module has been activated;
- The "Cypher System" mapping included in the settings for the module has been set;

When:
- A GM or an owning player opens a character's sheet;

Then:
- A link should appear on the title bar of the character sheet that allows the user to export the character's data to PDF.

### Current Behavior

Given: as above
When: as above
Then:
- No such button, link, or other access method is displayed on the title bar.

### Steps to Reproduce

1. Launch a world that uses the Cypher System game system.
2. Activate the "Export Sheet to PDF" module, click the "Save Module Settings" button and select "Yes" on the "Reload Application?" dialog that appears.
3. In the "Export Sheet to PDF" section of the "Configure Game Settings" dialog and select "cyphersystem" from the "Mapping" drop down. Click "Save Changes."
4. In the "Actors" tab of the sidebar, create a new Actor.
5. Observe that no link, button or other methodology to access the Export functionality appears on the title bar.

### Version

0.22.4

### Foundry VTT Version

11.306

### Operating System

Windows

### Browser / App

Native Electron App

### Game System

cyphersystem

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by gioppoluca** [comment]
In 5e I have recently added the option to have sheets also for NPC.
I need to check if there is an API for getting the actor sheet.
Will check.
For the moment could be a solution for you if I add also lower case "pc" in the next build?

**Comment by mrkwnzl** [comment]
Yeah, lower case `pc` will work.
